name: Add new link
description: You would like to add a new link to the collection
labels: ["🆕 new link"]
body:

  - type: input
    id: link
    attributes:
      label: URL of the article or project
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: >
        Explain the motivation for adding this link to the current collection. What's special about it?
      placeholder: |
        This new link is special because...
    validations:
      required: true

  - type: checkboxes
    id: affiliation
    attributes:
      label: Affiliation
      description: >
        Please indicate how you are associated with the new proposed content.
      options:
        - label: "I am the author of the article or project"
        - label: "I am working for/with the company which is publishing the article or project"
        - label: "I'm just a rando who stumbled upon this via social networks"
    validations:
      required: true

  - type: checkboxes
    id: self-checks
    attributes:
      label: Self checks
      options:
        - label: >
            I have [read the Code of Conduct
            ](https://github.com/kdeldycke/awesome-template/blob/main/.github/code-of-conduct.md)
        - label: >
            I applied all rules from the [Contributing guide
            ](https://github.com/kdeldycke/awesome-template/blob/main/.github/contributing.md)
        - label: >
            I have checked there is no other
            [Issues](https://github.com/kdeldycke/awesome-template/issues) or [Pull
            Requests](https://github.com/kdeldycke/awesome-template/pulls) covering the same topic
            to open
    validations:
      required: true