---
name: 🪄 Autofix
"on":
  workflow_dispatch:
  schedule:
    - cron: "27 4 * * 1"
  push:
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/repomatic/.github/workflows/autofix.yaml@66650046de54a8032f4c38358b7ef8c9ae39e7b5 # v7.11.0
    secrets:
      REPOMATIC_NOTIFICATIONS_PAT: ${{ secrets.REPOMATIC_NOTIFICATIONS_PAT }}
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
