---
name: 🪄 Autofix
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/repomatic/.github/workflows/autofix.yaml@c8f44f78ebc03da94c3fa9345e1978df504cc7e3 # v6.12.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
