---
name: 🪄 Autofix
"on":
  workflow_dispatch:
  schedule:
    - cron: "27 4 * * 1"
  push:
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/repomatic/.github/workflows/autofix.yaml@ef51d27ea435bf5368112791288130134bd02142 # v7.5.0
    secrets:
      REPOMATIC_NOTIFICATIONS_PAT: ${{ secrets.REPOMATIC_NOTIFICATIONS_PAT }}
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
