---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@ef51d27ea435bf5368112791288130134bd02142 # v7.5.0
