---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@46bf129bf3dcab284cef50c870e34f5f3859e860 # v6.15.0
