---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@f3fd0341a6ffbe9f948e78e3270ca30faf2b2459 # v7.4.1
