---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - changelog.md
      - citation.cff
      - "docs/**"
      - pyproject.toml
      - "readme.*.md"
      - readme.md
      - uv.lock
      - "**/*.py"
  schedule:
    - cron: "43 6 15 * *"

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@35cc8a45d65954faebaf8b4bb9960b525d446554 # v7.16.2
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
