---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - changelog.md
      - citation.cff
      - "docs/**"
      - pyproject.toml
      - readme.md
      - uv.lock
      - "**/*.py"

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@ef51d27ea435bf5368112791288130134bd02142 # v7.5.0
