---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - changelog.md
      - citation.cff
      - "docs/**"
      - pyproject.toml
      - readme.md
      - uv.lock
      - "**/*.py"

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@f3fd0341a6ffbe9f948e78e3270ca30faf2b2459 # v7.4.1
