---
name: 🏷️ Labels
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release
    types:
      - opened
  issues:
    types:
      - opened

jobs:

  labels:
    uses: kdeldycke/repomatic/.github/workflows/labels.yaml@f3fd0341a6ffbe9f948e78e3270ca30faf2b2459 # v7.4.1
