---
name: 🧹 Lint
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - prepare-release
      - "renovate/**"

jobs:

  lint:
    uses: kdeldycke/repomatic/.github/workflows/lint.yaml@46bf129bf3dcab284cef50c870e34f5f3859e860 # v6.15.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
