---
name: 🧹 Lint
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.gif"
      - "**/*.jpeg"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.svg"
      - "**/*.webp"
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release

jobs:

  lint:
    uses: kdeldycke/repomatic/.github/workflows/lint.yaml@f3fd0341a6ffbe9f948e78e3270ca30faf2b2459 # v7.4.1
    secrets:
      REPOMATIC_NOTIFICATIONS_PAT: ${{ secrets.REPOMATIC_NOTIFICATIONS_PAT }}
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
