---
name: 🧹 Lint
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.gif"
      - "**/*.jpeg"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.svg"
      - "**/*.webp"
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release

jobs:

  lint:
    uses: kdeldycke/repomatic/.github/workflows/lint.yaml@35cc8a45d65954faebaf8b4bb9960b525d446554 # v7.16.2
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      REPOMATIC_NOTIFICATIONS_PAT: ${{ secrets.REPOMATIC_NOTIFICATIONS_PAT }}
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
