---
name: 🆕 Renovate
"on":
  workflow_dispatch:
  schedule:
    - cron: "3 17 * * 1"
  push:
    branches:
      - main

jobs:

  renovate:
    uses: kdeldycke/repomatic/.github/workflows/renovate.yaml@46bf129bf3dcab284cef50c870e34f5f3859e860 # v6.15.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
